export function pipe<TInitial>(initial: TInitial) {
  function through<A>(fn0: (tinitial: TInitial) => A): A;
  function through<A, B>(fn0: (tinitial: TInitial) => A, fn1: (a: A) => B): B;
  function through<A, B, C>(fn0: (tinitial: TInitial) => A, fn1: (a: A) => B, fn2: (b: B) => C): C;
  function through<A, B, C, D>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
  ): D;
  function through<A, B, C, D, E>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
  ): E;
  function through<A, B, C, D, E, F>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
  ): F;
  function through<A, B, C, D, E, F, G>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
  ): G;
  function through<A, B, C, D, E, F, G, H>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
  ): H;
  function through<A, B, C, D, E, F, G, H, I>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
  ): I;
  function through<A, B, C, D, E, F, G, H, I, J>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
  ): J;
  function through<A, B, C, D, E, F, G, H, I, J, K>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
  ): K;
  function through<A, B, C, D, E, F, G, H, I, J, K, L>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
  ): L;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
  ): M;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
  ): N;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
  ): O;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
  ): P;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
  ): Q;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
  ): R;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
  ): S;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
  ): T;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
    fn20: (t: T) => U,
  ): U;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
    fn20: (t: T) => U,
    fn21: (u: U) => V,
  ): V;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
    fn20: (t: T) => U,
    fn21: (u: U) => V,
    fn22: (v: V) => W,
  ): W;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
    fn20: (t: T) => U,
    fn21: (u: U) => V,
    fn22: (v: V) => W,
    fn23: (w: W) => X,
  ): X;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
    fn20: (t: T) => U,
    fn21: (u: U) => V,
    fn22: (v: V) => W,
    fn23: (w: W) => X,
    fn24: (x: X) => Y,
  ): Y;
  function through<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z>(
    fn0: (tinitial: TInitial) => A,
    fn1: (a: A) => B,
    fn2: (b: B) => C,
    fn3: (c: C) => D,
    fn4: (d: D) => E,
    fn5: (e: E) => F,
    fn6: (f: F) => G,
    fn7: (g: G) => H,
    fn8: (h: H) => I,
    fn9: (i: I) => J,
    fn10: (j: J) => K,
    fn11: (k: K) => L,
    fn12: (l: L) => M,
    fn13: (m: M) => N,
    fn14: (n: N) => O,
    fn15: (o: O) => P,
    fn16: (p: P) => Q,
    fn17: (q: Q) => R,
    fn18: (r: R) => S,
    fn19: (s: S) => T,
    fn20: (t: T) => U,
    fn21: (u: U) => V,
    fn22: (v: V) => W,
    fn23: (w: W) => X,
    fn24: (x: X) => Y,
    fn25: (y: Y) => Z,
  ): Z;

  function through(...funcs: ((i: any) => any)[]) {
    return funcs.reduce((value, func) => func(value), initial);
  }
  return through;
}
